const ACTION_TYPES = {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  SET_STEP: "SET_STEP",
  USER_AUTH_SUCCESS: "USER_AUTH_SUCCESS",
  USER_LOGOUT: "USER_LOGOUT",
  SET_THEME: "SET_THEME",
  LIGHT_THEME: "LIGHT_THEME",
  DARK_THEME: "DARK_THEME"
}

export default ACTION_TYPES;