POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTQsImlhdCI6MTczOTU1Nzk5MSwiZXhwIjoxNzM5NTU4MDIxfQ.kUoCm6P33PwTRR46z2e2zVLKNgqdcKXU9HB6ofLtz2U"
}