POST http://localhost:3000/auth/registration
Content-Type: application/json

{
  "firstName": "User",
  "lastName": "Userenko",
  "isMale": true,
  "email": "user3@example4279.com",
  "password": "supersecurepassword123",
  "passwordRepeat": "supersecurepassword123"
}